openapi: 3.0.0
info:
  title: Checkout API Documentation
  description: This is the checkout API documentation file
  version: 1.0.0
servers:
  - url: http://localhost:3001
paths:
  /checkout:
    post:
      summary: Perform checkout
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                purchasedItems:
                  type: array
                  items:
                    $ref: "#/components/schemas/Item"
      responses:
        "200":
          description: Successful checkout
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CheckoutSuccess"
        "400":
          description: Bad request - Checkout failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CheckoutFailure"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Item:
      type: object
      properties:
        sku:
          type: string
        name:
          type: string
        price:
          type: number
        quantity:
          type: number
    Response Item:
      type: object
      properties:
        sku:
          type: string
        name:
          type: string
        quantity:
          type: number
        note:
          type: string
    Failed Item:
      type: object
      properties:
        message:
          type: string
        sku:
          type: string
        name:
          type: string
        reqQuantity:
          type: number
        exisQuantity:
          type: number
    CheckoutSuccess:
      type: object
      properties:
        success:
          type: boolean
          enum:
            - true
        items:
          type: array
          items:
            $ref: "#/components/schemas/Response Item"
        cost:
          type: number
    CheckoutFailure:
      type: object
      properties:
        success:
          type: boolean
          enum:
            - false
        details:
          type: array
          items:
            $ref: "#/components/schemas/Failed Item"
    Error:
      type: object
      properties:
        error:
          type: string
